### PR TITLE
delete Gemfile.lock from repository

### PR DESCRIPTION
**Pull request by haroon10725**
@pikurasa Can you please review it.

### CODE REVIEW

**Comment by pikurasa** [comment]
When I tried this, I couldn't get it to run without adding the following to the Gemfile: `gem "nokogiri", ">= 1.13.6", "< 2.0"`

Screenshot from 2024-10-28 21-40-16

*Disclaimer: I have hardly a clue what I'm doing, other than tinkering.*

@haroon10725 does it work when you add that to your Gemfile?

(Basically, I think we also need to update the Gemfile to ensure that we're grabbing the right dependencies.

**Comment by haroon10725** [comment]
@pikurasa I just deleted the Gemfile.lock file and executed this command "bundle exec jekyll serve --incremental". This automatically creates a Gemfile.lock file for me. Can you please try doing this way.

**Comment by quozl** [comment]
Ruby Gems are quite interesting.  There's much complexity hidden.  It may be worth starting a temporary project directory using the latest Jekyll documentation, then comparing the Ruby configuration between that directory and this repository.  Becomes an upgrade of Jekyll for us.

But I approve removal of the Gemfile.lock, as it is a generated file that is operating system specific.  Next question is whether the Sugar Labs infrastructure will continue to work, or if it will fail once this commit reaches master.  If it does fail, hopefully reverting the commit will fix it.  If not, need to get in to the server to find out what has gone wrong.

**Comment by quozl** [comment]
As this is a potential service-breaking commit, please make sure the commit message is a bit more than "delete Gemfile.lock"!

**Comment by pikurasa** [comment]
> @pikurasa I just deleted the Gemfile.lock file and executed this command "bundle exec jekyll serve --incremental". This automatically creates a Gemfile.lock file for me. Can you please try doing this way.

I am pointing something else out: I think that, at some point, we started relying on the gemlock file and the gemfile got out of date.

I found that `gem "nokogiri", ">= 1.13.6", "< 2.0"` needs to be added to the gemfile, but I suspect that there are other updates we need to make. Could you please look into this a little bit before we merge this?

**Comment by haroon10725** [comment]
@pikurasa Sure, will look into this.

**Comment by haroon10725** [comment]
`source "https://rubygems.org"
gem "jekyll", "~> 4.3.4"
gem "minima", "~> 2.5"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]`

**Comment by haroon10725** [comment]
@pikurasa I created a new Jekyll site, above is the Gemfile it generated for me. I swapped it with Sugar Labs website one and it worked. It also tells depreciated code used in our website. If you try it.

**Comment by pikurasa** [comment]
That works, and, yes, we're receiving some reports about the deprecated code, so that would be good to patch.

Please do me one last favor: It this PR, add the new code for the Gemfile. I recommend formatting it like this for readability:

```
source "https://rubygems.org"
gem "jekyll", "~> 4.3.4"
gem "minima", "~> 2.5"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12" end
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data" end
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
```

**Comment by haroon10725** [comment]
@pikurasa I have updated the PR.

**Comment by pikurasa** [comment]
@haroon10725 The website still works in production -- at least seems good so far -- and it says this patch resolved nine security issues.

Bravo!!!

**Comment by haroon10725** [comment]
Thankyou

**Comment by quozl** [comment]
Well done!

**Comment by haroon10725** [comment]
Thanks @quozl

**Pull request merged**
