### PR TITLE
Website Optimisation

### PR DESCRIPTION
**Pull request by sanatankc**
What have I done?

- [x] Removed render blocking Javascript
- [x] Minified googleFonts.css
- [x] Added HTML minifier 

What I haven't done?

- [ ] Enable Compression (I couldn't able to figure out, how to add gzip compression on a static site generator)
- [ ] Leverage Browser Caching (I have found a solution for this, we can host google analytics code on our server instead of google's server to leverage browser caching, there might be some downsides though.
- [ ]  Optimize CSS Delivery (We need to merge all css for this. I don't how to do it in jekyll without a task runner like Gulp)
- [ ] Reduce Server Response Time (No Idea for this :/)

### CODE REVIEW

**Comment by kipply** [comment]
You should ask to not do the browser caching, as hosting the files ourselves will stop the site from getting any updates. A lot of the kiwi files need to have the "correct" browser caching time set as well. The site is hosted on Github pages so there's not much you can do to reduce server response time. 

If you set up the site with `grunt`, that  should cover the CSS delivery, and make the dev process faster by minifying css/html/js as files are updated. (then minified files can be ignored) I have some experience with grunt let me know if you want a hand~

**Comment by sanatankc** [comment]
Yeah it is true though, that's why I didn't hosted files myself.

I myself know gulp and thinking to implement in the project.

**Comment by kipply** [comment]
I'll be happy to lend a hand since you're making the lives of future people much easier!

**Comment by quozl** [comment]
@kipply wrote:
> site is hosted on Github pages

sugarlabs.org is not hosted on GitHub Pages, and I don't know if any developer here is hosting on GitHub Pages, as there are no links to show that in the pull-request.

On the assumption that some of you _are_ temporarily hosting on GitHub Pages, and the performance effects are consequentially unknown; would a Sugar Labs web development instance be of use?  If so, write to the systems@ mailing list to start that discussion.

**Comment by kipply** [comment]
Ah sorry about that I assumed that the site was hosted on Github Pages since the "live preview" is on Github pages.

**Comment by quozl** [comment]
@kipply, what "live preview" do you see?  I've looked for one and can't see any.  Maybe I'm looking in wrong place.

**Comment by kipply** [comment]
@quozl The "Introduction" of the README specifies "A live preview of the website is hosted using Github pages and can be viewed at...", though I guess that live preview isn't being used anymore. Sorry for the confusion~

**Comment by quozl** [comment]
@kipply, thanks, the `README.md` was merged without removing task-specific information that is out of date, see also https://github.com/sugarlabs/www-sugarlabs/issues/140.  We host the _master_ branch content on our own server.

**Comment by kipply** [comment]
@sanatankc See #190

**Comment by sanatankc** [comment]
Yeah, I saw it. Thank you @kipply for implementing it.

**Comment by quozl** [comment]
Call for reviewers and testers.  Does this really improve performance by lowering data demand, or is our server already using compression?

**Pull request closed without merging**
