### PR TITLE
Resolve #191 Contributors page with GitHub contributors

### LINKED ISSUE #191: Contributors page proposal.
Having a list of contributors to an organisation not only gives all its contributors a token of appreciation but also emphasises on the human aspect of open source. But it isn't easy for Sugar Labs to implement this as many contributors are scattered inside repositories and the GitHub API doesn't give a complete list of contributors to an organisation(it just gives the members). We'd need to write a script to go through all our repositories and update that list periodically or we could just have the data from our top 5-10 repos. (i.e www-sugarlabs, sugar, sugar-docs, etc.)

During my last GCI I helped build this: https://zulipchat.com/team/ (Although it has changed a lot since the last time I looked at it. :p)

It'd be a pretty cool addition to add to our website. :D

### PR DESCRIPTION
**Pull request by FreddieN**
Resolve #191
For my GCI task, I made this contributors page which takes a JSON file generated by a python script (see here: https://github.com/FreddieN/Sugar-Labs-Contributor-Page).  I have also integrated the old profiles page into a “member list” which can be used for users who do not contribute on GitHub but still work with Sugar Labs. There is also opt out functionality. You can find more details on the actual data gathering in the readme in the repository linked.
The actual page looks like this:
https://i.imgur.com/Ce2yXoz.png
I have changed the navigation to point to this new page but if you want to have both /contributors and /profiles I can change it back.
Let me know what you think of it. 😊

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Interesting.

@chimosky, will the membership committee administer this?  It adds to the work load quite a bit, to ensure that all contributors are properly detected.  As it fixes #191. see there for details.

**Comment by chimosky** [comment]
@quozl thanks.

@FreddieN we have a [members list](https://wiki.sugarlabs.org/go/File:SL_Member_List_verified_2017.ods) and there's a difference between being a member and a contributor as you don't need to be a member to be a contributor.

I agree with @quozl in https://github.com/sugarlabs/www-sugarlabs/issues/191#issuecomment-355924869

If every data can be combined to a list of contributors as every member has made a contribution one way or another instead of having a members list on the website with people who aren't members, that'll be great. So instead of having a Members List on the website that isn't the same as the one on the wiki, we just have a list of contributors which takes everything into consideration.

**Comment by FreddieN** [comment]
@chimosky Thanks for taking a look, sorry I did not realise that we also had a members list. The "members list" I made was designed to replace the old profiles page. Users would be able to make a pull request to add their name to the CSV file in the generation repo (e.g. translators, wiki contributors etc). So are you suggesting I remove the member's list and combine it all into one single list? The open source section already get's every contributor to Sugar Repos by using the GitHub API.

**Comment by quozl** [comment]
Equity.  Many of our testers, translators and Wiki contributors can't or won't make pull requests.  People such as Thomas, our Fedora tester.  Almost every translator.  It would be unfair to exclude them.  That's why I noted that the committee would have to administer this.  It seems unlikely that the committee would be able to find the time, and contributors would be without credit.  My opinion is to solve this by removing the contributors page, but there seems interest in keeping it, even if it is as _badly_ maintained as it is now.  Hope you see my point.  :grinning:

**Comment by FreddieN** [comment]
For the wiki editors and translators, there is a possibility of adding them automatically. I think they both have APIs, however, the pootle one doesn't seem to have any member functionality. I get your point though on how people probably won't make PRs to get their names added and how it would add a load on to the committee to edit. I do think it's quite a nice feature to see all the people who have contributed to our repositories though.

**Comment by samswag** [comment]
I think it will be difficult to get everyone's data. Developers will benefit more than other contributors that don't use GitHub as a form of contributing. So but that solve the fact that the project is needed. I see that [zulipchat](https://zulipchat.com/team/) uses the same thing but it only focus on coders.

It is a tough call. FYI, have you tested this PR? is it working?  @FreddieN the image you sent is like a mockup, not the showing the propose contributors page.

**Comment by quozl** [comment]
Thanks.  Detailed code review;

* profiles is removed from `nav.html`, but not removed from `sitemap.txt`, and the `profiles.md` file remains as well; this seems inconsistent,
* profiles could be used for Sugar Labs Oversight Board member profiles,
* another off-site resource is added; showdown, but the site is already extremely slow; can this be put inline or on our server to avoid further slowing?

**Comment by FreddieN** [comment]
@samswag I've put it on my own server here: http://fr3ddie.me:4000/contributors . The reason I did not send originally is that I can't keep it up the whole time. But it is fully working.

@quozl 

- I thought I should have left the profiles.md for archive but removed it now to prevent any confusion.
- I like your idea of having a specific section for the Sugar Labs Oversight Board, it could be embedded in the same page similar to how [zulipchat](https://zulipchat.com/team/) has done it or have it's own profiles page like you suggested.
- I have committed showdown as a script on the server instead of being linked via CDN.

**Comment by samswag** [comment]
Good job. I don't think we should make our members list public, what do you think @chimosky? The purpose is to focus on contributors, not members. Yes, we can have the Sugar Labs oversight board visible on the website but not members.

How fast those the contributors list sync from Github because the list you provided shows 3rd of November.

**Comment by quozl** [comment]
@FreddieN, thanks.

@samsraag, Member list is already public on the Wiki.  How would this be different?  One can only be a member by contributing; it's in the rules.  So all members are contributors.  Why create a split between members and contributors when, in theory, there isn't one?

**Comment by samswag** [comment]
You are correct @quozl to be a member, one needs to be a contributor.  

@FreddieN I am guessing that the "member list" isn't from the official list like this [one](https://wiki.sugarlabs.org/go/File:SL_Member_List_verified_2017.ods), right?

**Comment by quozl** [comment]
clists.json contains me.  I'm a contributor, but not a member, intentionally.  So I guess the data comes from some other origin.

**Comment by samswag** [comment]
I was referring
screenshot 2018-11-07 at 12 19 26 am
 to this list

**Comment by quozl** [comment]
Well, I'm looking at the [cumulative patch](https://github.com/sugarlabs/www-sugarlabs/pull/251/files) and the only thing that contains those names is clists.json.

**Comment by FreddieN** [comment]
@samswag @quozl I've renamed the Member List to Profile List to make it clearer. It is just the old profiles.md data with the relevant descriptions in a modal on click. At the moment the member's list on the wiki is not on this, however, it could be easily added to the members.csv file in the generation repo.

The data has to be generated off-site due to a large amount of data that has to process to form the list. It is quite simple to generate, it just takes a few minutes I was thinking you might have been able to implement some sort of automated execution on the server but otherwise, it could just be updated once a month by a PR?

**Comment by quozl** [comment]
We do have automatic execution on the server; in particular triggered when a commit is added to the master branch.  I don't yet know who manages that automation.  Can what is in your generation repo be safely part of this repo?  That is, hidden from Jekyll or the server.

**Comment by chimosky** [comment]
> @chimosky Thanks for taking a look, sorry I did not realise about the member's list. The list was designed to replace the old profiles page. Users would be able to make a pull request to add their name to the CSV file in the generation repo (e.g. translators, wiki contributors etc). So are you suggesting I remove the member's list and combine it all into one single list? The open source section already get's every contributor to Sugar Repos by using the GitHub API.

@FreddieN Yes it'll be great to remove the `Members List` and combine it into one `Contributors List` as this looks at everyone from the wiki to translations to testers as not everyone will make a PR as @quozl has said.

**Comment by chimosky** [comment]
> Good job. I don't think we should make our members list public, what do you think @chimosky? The purpose is to focus on contributors, not members. Yes, we can have the Sugar Labs oversight board visible on the website but not members.

I agree as the focus isn't on members but contributors.

**Comment by quozl** [comment]
https://github.com/sugarlabs/www-sugarlabs/pull/255 also deletes profiles.md; do you need to rebase?

**Comment by samswag** [comment]
@FreddieN Apologies, I didn't realize that merging #255 was going to affect this work. If possible, can you continue?

**Comment by FreddieN** [comment]
@chimosky 
I have now combined all the lists into one grid. 
demo

Do you think this combined grid is a good approach or do you think it could be done in a better way?

I have written the script for getting the wiki contributors however it requires access to the wiki database which I do not have access to (https://github.com/FreddieN/Sugar-Labs-Contributor-Page/blob/master/wiki/getWikiContributorsSQL.py). For the translators, I saw it as a task on GCI and it has now disappeared so I presume it has been completed. Once I have these lists I can implement the functionality to link to their pages.

**Comment by chimosky** [comment]
> Do you think this combined grid is a good approach or do you think it could be done in a better way?

This looks great

> I have written the script for getting the wiki contributors however it requires access to the wiki database which I do not have access to (https://github.com/FreddieN/Sugar-Labs-Contributor-Page/blob/master/wiki/getWikiContributorsSQL.py)

@quozl can you help with this.

> For the translators, I saw it as a task on GCI and it has now disappeared so I presume it has been completed. Once I have these lists I can implement the functionality to link to their pages.

Yeah it's been completed, it's [here](https://github.com/aryanharitsh123/Info.-Scrapping-Script), although there's some reservations that the data collected isn't correct, it'll be great if you collect yours and cross examine with this.

**Comment by quozl** [comment]
Not the right place to ask.  We had people working on a Sugar Labs developer dashboard in the past year, and they also had a focus on tracking Wiki contributors, so please ask more widely.  Perhaps they completed something better.

**Comment by jonasmd18** [comment]
Very good !! my <a rel="dofollow" href="https://www.desentupidorahidrolux.com.br">Desentupidora Pinhais</a>

**Pull request closed without merging**
