### PR TITLE
 issue#321 Social accounts open in new tab

### PR DESCRIPTION
**Pull request by himanshujaidka**
Now, it opens in a new tab

### CODE REVIEW

**Comment by quozl** [comment]
Why would anyone want that?  Forces the user to close one more tab.

**Comment by himanshujaidka** [comment]
Because it will easy for users who wants to compare one tab with another and many users will forget to close first tab that is sugarlabs tab and this website will remain open

**Comment by quozl** [comment]
Then they can use open in new tab feature.

**Comment by himanshujaidka** [comment]
if they are using a mobile phone then

**Comment by himanshujaidka** [comment]
In my point of view, it is more convenient for the user when the link automatically opens in a new tab :)

**Comment by quozl** [comment]
This in conjunction with other recent issues and pull requests looks like a denial of service attack on our organisation.  Could you please explain why you have become interested in our web site?  Has someone asked you to be involved?  Is there a bounty?  Are we on some list somewhere?  I'd like to get us removed from any such list.

**Comment by himanshujaidka** [comment]
No! nothing like that :) Actually I want to take part in GSoC 2021 so for that I am preparing and I am very passionate about it. Would you mind if you will guide me and I also want to improve your website because I love to design websites :)

**Comment by quozl** [comment]
Thanks!  Looking at your profile, we could really do with help on Sugar, Sugarizer and Music Blocks.

**Comment by himanshujaidka** [comment]
ok

**Comment by olawanlejoel** [comment]
But I believe opening social accounts on a new tab is very useful as it helps uses still maintain what they were previously going through. I know users can easily take the 'open on a new tab' route but would be cool if it's integrated. 

The contributor can also add `rel="noopener"` with the `target="_blank"`

**Comment by samswag** [comment]
@olawanlejoel I agree too, but at the moment we are focusing on fixing some broken UI elements on the site. See #316

**Comment by himanshujaidka** [comment]
I think it is also a part of UI @samswag

**Comment by himanshujaidka** [comment]
ok @olawanlejoel I got it

**Pull request closed without merging**
