### PR TITLE
Float icon back to top

### PR DESCRIPTION
**Pull request by Devmoni**
### Description

This PR updates the visibility behavior of the 'Back to Top' button. Instead of being only in the footer, the button now appears when the user scrolls down the page by 30%. This change improves the user experience by providing quicker access to the top of the page.

### CODE REVIEW

**Comment by quozl** [comment]
Is this feature also available in later versions of Bootstrap and Airspace?  If so would it be better to upgrade?

**Comment by Devmoni** [comment]
This feature is implemented using only JavaScript and simple CSS, ensuring that it does not alter any core CSS of Bootstrap and Airspace.

I believe this can be useful since the site is quite long, helping users reach the top with just one click.

**Comment by quozl** [comment]
You didn't answer my question.  I've checked, and I can find nothing in either Bootstrap or Airspace latest releases to indicate that the feature is provided by either library.

**Comment by quozl** [comment]
Thanks.  My questions were about implementation and retaining our upgrade paths.  I am surprised this feature isn't in the libraries or themes we are using, but we are behind by a fair bit.

You do keep advocating afresh for your feature.  These can go into the commit message rather than the pull request.

(For myself, I find return to top buttons visually distracting and waste horizontal space at the lower edge of the view port.  I already know how to scroll to top, and don't need no web site to give me again a feature the browser already has.  Sure, there are people who don't know how to run their browser, but we're not an online gambling site.  We depend on prior learning to deliver the message that learning is critical for those in the care of the reader.).

@pikurasa please review; is this feature something you want?

**Comment by quozl** [comment]
Please resolve conflicts.

**Comment by Devmoni** [comment]
I have resolved the conflicts as requested.

**Comment by quozl** [comment]
https://github.com/sugarlabs/www/pull/612 does replace or augment this pull request?  If replace, please close this one.  Thanks.

**Comment by Devmoni** [comment]
No, as I separated #612 since it’s just a suggestion for the existing banner.

**Review by pikurasa — APPROVED** [review]
Tested. Looks good.

**Pull request merged**
