### PR TITLE
added FAQ page

### PR DESCRIPTION
**Pull request by therealharshit**
The page looks like this
Vedio:

https://github.com/user-attachments/assets/54265a4b-815d-456d-9dea-4ebad33e5c2d

I have taken the FAQs from https://wiki.sugarlabs.org/go/Sugar_Labs/FAQ

@pikurasa please review.

### CODE REVIEW

**Comment by therealharshit** [comment]
@pikurasa it follows the .MD workflow which we have discussed.

**Comment by quozl** [comment]
Your changes to airspace.css go against a long term goal of using a theme without changes.  See https://github.com/sugarlabs/www/issues/305

Should your changes to the file be in another file?

**Comment by pikurasa** [comment]
> Should your changes to the file be in another file?

@therealharshit I think it would be wise to put that sort of CSS change into a new CSS file called custom.css

Please make that change when you have the chance.

**Comment by therealharshit** [comment]
> Your changes to airspace.css go against a long term goal of using a theme without changes. See #305
> 
> Should your changes to the file be in another file?

made the changes @pikurasa @quozl rather than changing airspace.css or creating a new CSS file, I have used bootstrap utility classes.

**Comment by pikurasa** [comment]
@therealharshit It's not showing up for me in its current state:

Screenshot from 2024-10-28 22-16-45

**Comment by therealharshit** [comment]
@pikurasa that's strange, please make some changes to FAQ.html so that it regenerate I think the html file needs regeneration to reflect changes.

**Comment by pikurasa** [comment]
> @pikurasa that's strange, please make some changes to FAQ.html so that it regenerate I think the html file needs regeneration to reflect changes.

We've been tinkering around with gemfile and gemfile.lock, and I suspect this may have something to do with the issue.

Can you upload those files -- not in your PR but -- as a .zip file here, please?

**Comment by therealharshit** [comment]
[gemfiles.zip](https://github.com/user-attachments/files/17578185/gemfiles.zip)
@pikurasa I have uploaded those files but I don't think it has something to do with this issue.
I also request you to please try my proposed solution which is to make some changes to FAQ.html so that it regenerate I think the html file needs regeneration to reflect these kind of changes.

**Comment by pikurasa** [comment]
> I also request you to please try my proposed solution which is to make some changes to FAQ.html so that it regenerate I think the html file needs regeneration to reflect these kind of changes.

I tried making a change to FAQ.html, but I still cannot see the FAQ on the page...

Also, I wouldn't know why a manual change would be necessary, as it rebuilds when the branch is checked out.

**Comment by quozl** [comment]
Interesting.  Build is giving a warning, which may be preventing something from working.

On the repository view, go to settings, then Pages, then where it says 'Last deployed by @pikurasa 5 hours ago" click on the deployed link; 

https://github.com/sugarlabs/www/actions/runs/11631167617 says 

"The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/"

I don't know if it was saying this before the recent Gemfile changes.

**Comment by pikurasa** [comment]
@therealharshit I was able to get it to work by removing `--incremental` flag when building.

However, I wonder, should we put custom JS into a different file as well (e.g. a new "custom.js" file) -- WDYT?

**Comment by therealharshit** [comment]
> @therealharshit I was able to get it to work by removing `--incremental` flag when building.
> 
> However, I wonder, should we put custom JS into a different file as well (e.g. a new "custom.js" file) -- WDYT?

@pikurasa custom.js sounds good, I'll put the js code in that file and update my PR.

**Comment by therealharshit** [comment]
@pikurasa I have put the JS code in custom.js file and also linked it to base.html, please review.

**Pull request merged**
