### PR TITLE
fix: navbar layout for Sugar Labs website

### LINKED ISSUE #478: Navbar is not rendering on mobile
Currently, Navbar does not seem to be rendering on mobile (tested on Android and Chromium's dev tools).

Screenshot from 2024-10-13 18-26-32

I'm not sure when the last time it did work. I remember hearing from someone that something was broken on mobile related to the logo or the navbar, but the logo seems to be rendering.

### PR DESCRIPTION
**Pull request by haroon10725**
Fixes #478

https://github.com/user-attachments/assets/0da259eb-4f5c-46db-96fc-269c0011228b

### CODE REVIEW

**Comment by haroon10725** [comment]
@pikurasa Can you please review it.

**Comment by therealharshit** [comment]
@haroon10725 how did you test this, I find everything is not fixed yet.

**Comment by haroon10725** [comment]
Can your share screenshots ?

**Comment by therealharshit** [comment]
> I have tested it, you can refer to the video.

Sure, I will make.

**Comment by therealharshit** [comment]
@haroon10725 your changes are only working on the home page (index.html), when we navigate to other pages (like I did for press page) it's still broken

https://github.com/user-attachments/assets/d99cf500-c72d-4b3f-9036-355eefff51d2

**Comment by therealharshit** [comment]
@haroon10725 @pikurasa I have fixed everything in my PR #503 and I think no further changes are required.

**Comment by pikurasa** [comment]
@haroon10725 thank you. I think your input was helpful in solving this.

**Pull request closed without merging**
