### PR TITLE
Fixed deprecated sass functions

### PR DESCRIPTION
**Pull request by mohanamisra**
`darken()` is a deprecated global built-in function. It uses a legacy method for color manipulation that lead to several deprecation warnings on the terminal at best, and can lead to inconsistent results at worst (see [what the sass documentation has to say about it](https://sass-lang.com/documentation/breaking-changes/import/)).

 `color.adjust()` provides a more modern, flexible, and predictable approach to adjusting specific color properties and is the recommended approach by the official sass documentation.

I have replaced the deprecated `darken()` function with `color.adjust()` to have the exact same visual effect for the viewer as intended by the original design.

##### Before (using deprecated `darken()`)

before (1)

7f6da252-d2b2-4f4e-af20-15de241c2990

##### After (using recommended `color.adjust()`)

after (1)

ded5e28f-ff03-43ed-8efb-b4003ff79ac7

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.  Looks good.  Next time, your explanation would be better in the commit message, without images.

**Comment by pikurasa** [comment]
@quozl It seems that 2326de43016de072de92e3a858ed93a7ee09968f is causing a build failure (see: https://github.com/sugarlabs/www/actions/runs/11900057084).

I'm tempted to revert that change. WDYT?

@mohanamisra do you know why that would cause any troubles?

The full error is here:
```
Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v232 GitHub Pages: jekyll v3.10.0 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /node_modules EntryFilter: excluded /CNAME EntryFilter: excluded /Gemfile Reading: _posts/2008-05-15-New-foundation-focused-on-taking-the-Sugar-user-interface-to-the-next-level-of-usability-and-utility.md Reading: _posts/2008-12-09-Sugar-Labs-joins-the-Software-Freedom-Conservancy.md Reading: _posts/2009-03-16-La-Asociación-sin-fines-de-lucro-Sugar-Labs-Anuncia-su-Nueva-Versión-de-la-Plataforma-de-Aprendizaje-Sugar-para-Niños-que-Funciona-en-Notebooks-y-PCs.md Reading: _posts/2009-03-16-Sugar-Labs,-organisation-à-but-non-lucratif,-annonce-la-sortie-de-la-nouvelle-version-de-la-plateforme-d’apprentissage-pour-enfants-Sugar-pour-PC-et-netbooks.md Reading: _posts/2009-03-16-Sugar-Labs-Nonprofit-Announces-New-Version-of-Sugar-Learning-Platform-for-Children,-Runs-on-Netbooks-and-PCs.md Reading: _posts/2009-03-16-Sugar-Labs-kündigt-neue-Version-von-Sugar-an—die-Lernplattform-für-Kinder-läuft-auf-Netbooks-und-PCs.md Reading: _posts/2009-04-22-Sugar-Labs-Announces-Beta‑1-of-Sugar-on-a-Stick,-LiveUSB-Version-of-Sugar-Learning-Platform-for-Children.md Reading: _posts/2009-04-22-Sugar-Labs-annonce-la-bêta-1-de-Sugar-on-a-Stick,-version-LiveUSB-de-Sugar,-la-plate-forme-d’apprentissage-pour-enfants.md Reading: _posts/2009-06-24-Sugar-Labs-Announces-Immediate-Availability-of-Sugar-on-a-Stick;-Learning-Platform-Runs-on-Any-PC-or-Netbook-In-The-Classroom.md Reading: _posts/2009-06-24-Sugar-Labs-annonce-la-disponibilité-immédiate-de-«-Sugar-on-a-Stick-»,-une-plate-forme-d’apprentissage-qui-fonctionne-sur-n’importe-quel-PC-ou-netbook-dans-la-salle-de-classe.md Reading: _posts/2009-06-24-Sugar-Labs-annuncia-l’immediata-disponibilità-di-Sugar-on-a-Stick;-La-Piattaforma-di-Apprendimento-in-grado-di-funzionare-su-qualsiasi-PC-o-Netbook-disponibile-in-classe.md Reading: _posts/2009-06-24-Sugar-Labs-anuncia-la-disponibilidad-inmediata-de-Sugar-On-A-Stick-(Sugar-en-un-pendrive).-El-plataforma-de-aprendizaje-funciona-en-casi-cualquier-PC-o-portátil-que-hay-en-el-aula..md Reading: _posts/2009-06-24-Sugar-Labs-gibt-die-Veröffentlichung-von-Sugar-on-a-Stick-bekannt;-die-Lernplattform-läuft-auf-jedem-PC-oder-Netbook-im-Klassenzimmer..md Reading: _posts/2009-06-24-Sugar-Labs-kondigt-aan-dat-Sugar-on-a-Stick-nu-beschikbaar-is;-dit-leerplatform-draait-op-elke-pc-of-netbook..md Reading: _posts/2009-11-18-Sugar-Labs-and-Free-Software-Foundation-Celebrate-Software-Freedom-Day,-Announce-Joint-Efforts-to-Promote-the-Sugar-Learning-Platform-for-Children-Worldwide.md Reading: _posts/2009-12-08-Gemeinnütziges-Sugar-Labs-gibt-zweite-Version-von-Sugar-on-a-Stick-frei-mit-verbesserter-E-Book-Unterstützung,-macht-aus-jedem-USB-Stick-eine-Lernumgebung-für-Kinder;-Partnerschaft-mit-Nexcopy,-Inc..md Reading: _posts/2009-12-08-Sugar-Labs-Nonprofit-Announces-v2-of-Sugar-on-a-Stick-with-Improved-E-Book-Readers,-Recycles-Any-USB-Stick-Into-Learning-Environment-for-Children;-Partners-with-Nexcopy,-Inc..md Reading: _posts/2010-04-29-L'Office-de-secours-et-de-travaux-des-Nations-unies-choisi-les-ordinateurs-du-projet-One-Laptop-per-Child-et-la-plate-forme-Sugar-pour-un-projet-majeur-d'éducation-au-proc
```

Warning:
```
The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/
```

**Comment by mohanamisra** [comment]
@pikurasa I apologise for the issue. While I see the error, I cannot exactly replicate it on my system. I can't see exactly why this error would occur, considering the change didn't even require me to update any libraries, and would have to investigate further.

**Comment by pikurasa** [comment]
@mohanamisra if we don't figure out why these changes are causing build to fail and how to fix it, we may need to revert these changes in order to get build working again. The live site doesn't seem to be rendering changes made after this commit, which is problematic.

**Comment by quozl** [comment]
Yes, go ahead and revert until it works again.  Sorry, busy at the moment otherwise I'd try it.  As a production issue, feel free to push directly to master, or do resetting head and force pushing.

**Comment by mohanamisra** [comment]
> @mohanamisra if we don't figure out why these changes are causing build to fail and how to fix it, we may need to revert these changes in order to get build working again. The live site doesn't seem to be rendering changes made after this commit, which is problematic.

Sure, that's no issue at all. The error confuses me a little and I'm not sure why changing a function caused this. I'll see what I can find out but getting the live site as it was is definitely the bigger priority.

**Comment by pikurasa** [comment]
@mohanamisra would you mind to submit a PR that reverts the change? That would help me out.

Please make sure it only has changes pertinent to undoing this PR.

**Comment by pikurasa** [comment]
> > @mohanamisra would you mind to submit a PR that reverts the change? That would help me out.
> > Please make sure it only has changes pertinent to undoing this PR.
> 
> Of course. Is it okay if I do that tomorrow, however?

yes

**Comment by pikurasa** [comment]
@mohanamisra FYI, I need to publish some content today, so I am reverting the change myself now.

**Comment by mohanamisra** [comment]
> @mohanamisra FYI, I need to publish some content today, so I am reverting the change myself now.

I actually did make a PR.

**Pull request merged**
