### PR TITLE
Restore color changing logo feature and Fixes #564

### LINKED ISSUE #564: Can't read properties of null error upon opening the website
When I am opening the website, I get this error. 

Screenshot (478)

### PR DESCRIPTION
**Pull request by therealharshit**
I have restored the color changing logo feature which also fixes #564 .

Now the logo is responsive and working on all screen sizes:

https://github.com/user-attachments/assets/96445574-4ef1-4d47-b13c-b400ec3231e8

@quozl @pikurasa please review.

### CODE REVIEW

**Comment by pikurasa** [comment]
@aneesafatima , @yashsaraswat2004 will you be able to follow-up and review this?

If you have questions about the process, please ask in https://matrix.to/#/#sugarlabs-web:matrix.org

**Comment by quozl** [comment]
@therealharshit could you please rebase the branch to remove the merge commit?  Merge commits make git history more difficult to use.  I did try rebasing myself, but there were conflicts and I ran out of time.

**Comment by therealharshit** [comment]
> @therealharshit could you please rebase the branch to remove the merge commit? Merge commits make git history more difficult to use. I did try rebasing myself, but there were conflicts and I ran out of time.

@quozl This PR git to many commit, so I have raised a new PR #587 please review that and you can close this.

**Comment by quozl** [comment]
> @quozl This branch got to many commit, so I have pushed a new branch in PR #587 please review that and you can close this.

In future you can and should interactive rebase to rewrite commits and force push, so that we don't have to switch to a new pull request.

**Comment by therealharshit** [comment]
> > @quozl This branch got to many commit, so I have pushed a new branch in PR #587 please review that and you can close this.
> 
> In future you can and should interactive rebase to rewrite commits and force push, so that we don't have to switch to a new pull request.

@quozl Thanks for the suggestion, I'll make sure to follow this approach in the future.

**Pull request closed without merging**
