### PR TITLE
Fixes #537 beautify _posts

### LINKED ISSUE #537: Make our _posts less ugly
Everything rendered from _posts is rendering quite ugly.

Examples:
* https://www.sugarlabs.org/community/2024/09/20/sweet-spot/
* Everything under: https://www.sugarlabs.org/event/
* Everything under: https://www.sugarlabs.org/press/

Some specific "ugliness":
* The markdown bullets don't seem to be rendering as bullets
* There is no border, which makes it hard to read
* There is not enough space before headers, which also makes it hard to read.

### PR DESCRIPTION
**Pull request by therealharshit**
fixes #537 
@pikurasa I tried to beautify posts, this is how it looks.

Vedio:

https://github.com/user-attachments/assets/d33ceca8-22c5-48a4-b905-c99860f6c941

### CODE REVIEW

**Comment by pikurasa** [comment]
It's  certainly an improvement, and it's just at the time I need it.

So thank you!

That said, there's still something going on with the bullets and other markdown elements that I don't quite understand. They're not rendering as I would've expected.

**Comment by therealharshit** [comment]
> It's  certainly an improvement, and it's just at the time I need it.
> 
> So thank you!
> 
> That said, there's still something going on with the bullets and other markdown elements that I don't quite understand. They're not rendering as I would've expected.

I'll try to fix that.

**Comment by Ajaykumar724** [comment]
how to clone this project @therealharshit
pls explain me

**Comment by therealharshit** [comment]
hello @Ajaykumar724 you can read the documentation on "how to run this code" and join https://matrix.to/#/#sugarlabs-web:matrix.org for any discussion.

**Pull request merged**
