### PR TITLE
Adjusted footer for mobile visibility

### LINKED ISSUE #439: Footer links not visible on mobile
Right now footer links are only visible on desktop.

I made a screencast that I can upload, if needed, but you can test by going to www.sugarlabs.org on a phone and scrolling to the bottom.

This is a problem as some of the important links are not displayed on mobile.

### PR DESCRIPTION
**Pull request by soumyaranjan-panda**
# Issue: #439 
Fixes #439

## Tablet View
PS: Red dashed line in dev mode only. Disappears in production

## Mobile View
PS: Red dashed line in dev mode only. Disappears in production

### CODE REVIEW

**Comment by soumyaranjan-panda** [comment]
# Before
desktop

**Comment by soumyaranjan-panda** [comment]
Kindly review it,
@pikurasa @chimosky

**Comment by pikurasa** [comment]
It works for me for a test doing emulation in Chromium. And I think this solution is fine for now.

@chimosky perhaps you have some feedback as well?

**Comment by chimosky** [comment]
Tested, works as expected. Thank you @soumyaranjan-panda!

**Pull request merged**
