### PR TITLE
Make Donation Banner Responsive and Sync Logo Colors Dynamically,

### PR DESCRIPTION
**Pull request by saumyashahi**
## Summary

Enhance the donation banner's responsiveness to ensure it adapts to all screen sizes. Synchronize the banner's color with the dynamically changing logo color on each page reload.

- Fixes: #579 , #574 , #575

## Changes Made

- Add media queries to adjust the banner layout for different screen sizes.  
- Implement a JavaScript function to dynamically fetch and apply the logo color to the banner.

## Testing

- Verified the banner's layout and design across various screen sizes using browser developer tools.  
- Confirmed that the logo and banner colors synchronize correctly on every page reload.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Please resolve conflicts.

**Comment by saumyashahi** [comment]
> Thanks. Please resolve conflicts.

@quozl I have resolved all merge conflicts. Thanks for reviewing !

**Comment by quozl** [comment]
Thanks.

Could you use sugar-artwork:icons/scalable/actions/entry-stop.svg instead of acquiring the assets/close-x-svgrepo-com.svg?

As the commits on this branch are mixed authorship, it would be improper of us to squash and merge.  So we must place more emphasis on the commit ordering, as that will appear in git history.

Please squash the merge and merge conflicts into the commits prior to them.  If you've not done this, look at `git rebase -i` documentation.

Also, please use our [guide to making commit messages](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits).  Several of the commit messages don't follow our guidance.

Thank you!

**Comment by saumyashahi** [comment]
Okay I'll look into it and complete it asap

**Comment by saumyashahi** [comment]
@quozl 

> Could you use sugar-artwork:icons/scalable/actions/entry-stop.svg instead of acquiring the assets/close-x-svgrepo-com.svg?

I have used the close icon from the sugar-artworks repository, and removed the close-x-svgrepo-com.svg file.

> As the commits on this branch are mixed authorship, it would be improper of us to squash and merge. So we must place more emphasis on the commit ordering, as that will appear in git history.
> 
> Please squash the merge and merge conflicts into the commits prior to them. If you've not done this, look at `git rebase -i` documentation.

I was particularly new to this, I have merged and resolved conflicts with `git rebase -i` , thanks for the reference documentation!

**Comment by pikurasa** [comment]
I just checked briefly.

Is it fetching images remotely for the images at the sides? (See image below)

Screenshot from 2024-12-23 14-17-29

If so, I think we should add to the repo and fetch them locally.

**Comment by quozl** [comment]
I've looked and can't find a remote image load.

Some of the image paths use `\` instead of `/`.

Some files have missing newline.

There are indentation changes to custom.js.

Please resolve these and remove the merge commit.  Thanks.

**Comment by saumyashahi** [comment]
@pikurasa 
> If so, I think we should add to the repo and fetch them locally.

I have changed the image paths, and I hope this resolves the issue.

@quozl 
> Please resolve these and remove the merge commit. Thanks.

I have resolved the issue and removed the merge commits with rebase, I hope there are no further conflicts.

**Comment by saumyashahi** [comment]
@pikurasa 
> If so, I think we should add to the repo and fetch them locally.

I have changed the image paths and added a base path to ensure compatibility for nested URLs.

@quozl 
> Please resolve these and remove the merge commit. Thanks.

I have removed the merge commits using rebase. I hope there are no further conflicts.

**Comment by saumyashahi** [comment]
> I think will only complicate the things. I have found a better solution for it. Testing it and create a PR for it.
>
> @saumyashahi Why did you used base tag?

I used the `<base>` tag to fix asset paths breaking in nested routes. It ensures consistent resolution across all pages and does not slow down the site or introduce external dependencies.

Using `<base href="/">` treats the root of the website as the starting point for all relative URLs, ensuring assets are fetched from their correct locations, avoiding errors, and improving overall path resolution efficiency. It’s a straightforward and efficient solution for this issue.

**Comment by haroon10725** [comment]
@saumyashahi What if we use svg?

**Comment by haroon10725** [comment]
@saumyashahi Sounds good.

**Comment by pikurasa** [comment]
I'm merging this.

We can continue to make improvements, both to the code and to our git habits, going forward.

**Comment by saumyashahi** [comment]
>I'm merging this

I’m thrilled to have made my first contribution to Sugar Labs. Looking forward to many more contributions!

**Pull request merged**
