### PR TITLE
Updated the Carousel 

### PR DESCRIPTION
**Pull request by Nama21yo**
https://github.com/user-attachments/assets/5022d5fa-eece-4d52-94a2-8fe2bd7e18ef

Ref #521 I have added a Bootstrap carousel to the Testimonials section, with custom CSS for improved styling and responsiveness. The navigation controls and indicators are styled for better usability, and the overall design complements the existing layout without disrupting the legacy theme.

### CODE REVIEW

**Comment by quozl** [comment]
Why change airspace.css?

**Comment by quozl** [comment]
There's too much irrelevant change, I can't see what you've really changed, and your commit messages don't explain.

**Comment by Nama21yo** [comment]
> Why change airspace.css?

I updated airspace.css to add some cool effects to the slider, like smooth transitions and hover animations, to make it look better and feel more interactive.

**Comment by Nama21yo** [comment]
> There's too much irrelevant change, I can't see what you've really changed, and your commit messages don't explain.

Okay other than the HTML and CSS I have added a cdn of js files to ensure the carousel functions properly. 
```
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
```

**Comment by quozl** [comment]
Thanks.

We'd like not to update files that come from themes or other software projects, so your change to airspace.css while in keeping with some of the earlier unfortunate work by others isn't helping toward minimising change against upstream themes.  Can you place your changes in a more appropriate place?

You've added CDN of JavaScript.  We've preferred to deliver all CSS from our own server, which has a type of CDN already.  If you've found the carousel functions improperly using our own server, we want to fix that rather than introduce more load-time dependency on an external organisation.

Please remove your changes to indentation so that the view of the pull request by files changed shows what you intend without extra things.

**Comment by pikurasa** [comment]
@Nama21yo What you created visually looks nice.

What @quozl is saying about calling the JS is correct; we need to avoid that.

As for custom CSS, please put that into the custom.css file.

**Comment by Nama21yo** [comment]
> @Nama21yo What you created visually looks nice.
> 
> What @quozl is saying about calling the JS is correct; we need to avoid that.
> 
> As for custom CSS, please put that into the custom.css file.

Okay the problem was with my vs code extension called prettier it formats the code and gives spacing that why it looks formatted too much and yes I shan't integrated CDN of js for carousel since it exists sorry I will correct it in my next PR on another issue.

**Comment by quozl** [comment]
Okay, that's expected.  Turn off reformatting extensions for functional pull requests.  Turn on reformatting extensions for new files only, or where a pull request is _only_ for reformatting.

Otherwise review is very difficult.

**Comment by therealharshit** [comment]
This issue has been fixed in bfcb246db65654d3ea822067730d39e317ecfdc0

**Comment by quozl** [comment]
That's great, but please submit the changes in  bfcb246 in the form of a pull request.

I see this pull request doesn't have the change in that form, and was based on your _master_ branch.  We recommend branching before making a pull request, see https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#branching

**Comment by Nama21yo** [comment]
> Oh, I see, bfcb246 is also on master branch now.  Thanks @therealharshit.  @Nama21yo do you want this pull request to proceed?
No , @quozl   
@therealharshit has resloved the issue with optimized code I will proceed on another issue.

**Comment by quozl** [comment]
Thanks!  Closing.

**Pull request closed without merging**
