### PR TITLE
Add a draft of an announcement

### PR DESCRIPTION
**Pull request by pikurasa**
You can test the draft by running `bundle exec jekyll serve --drafts`

Once we get it the way we want it, we copy it over with the YYYY-MM-DD-name.md naming convention; and, then, it should automagically create the html.

### CODE REVIEW

**Comment by pikurasa** [comment]
And it looks like this:

Screenshot from 2024-05-08 14-29-03
Screenshot from 2024-05-08 14-28-31

**Comment by quozl** [comment]
So it didn't appear on the web site.  I've run out of time for the moment, but next step is to check the automatic deployment process, or rename the file to match the convention in the hope that the date in the file name may be important.

**Comment by pikurasa** [comment]
> So it didn't appear on the web site. I've run out of time for the moment, but next step is to check the automatic deployment process. Given that you got it working locally, it should be fine.

I wouldn't expect it to appear yet.

It needs to be moved from _drafts folder to _posts folder.

The workflow should be: review it "as draft", approve it, then we deploy it "as post".

**Comment by pikurasa** [comment]
This is a PR for the last step of deploy as a post: https://github.com/sugarlabs/www/pull/433

**Pull request merged**
