### PR TITLE
New Colours for Activities Icons.

### PR DESCRIPTION
**Pull request by Thusal06**
Look at **the colors of activities icons** designed by me.

### CODE REVIEW

**Comment by quozl** [comment]
These are not the Sugar colours.

The images do not render when the file is viewed.

**Comment by samswag** [comment]
I agree with @quozl.  Instead, if you fancy, you might want to look into #316.

**Comment by Thusal06** [comment]
No, the pictures are rendering. Just cut and paste the links.

**Comment by Thusal06** [comment]
> These are not the Sugar colours.
> 
> The images do not render when the file is viewed.

I didn't know, you are supposed to use Sugar colors. Sorry!

**Comment by quozl** [comment]
I'm surprised you didn't notice.  Which version of Sugar have you been using?  See also discussion in https://github.com/sugarlabs/www-sugarlabs/issues/174

**Pull request closed without merging**
