### PR TITLE
I don't believe we have Mailchimp integration, so I'm removing it

### PR DESCRIPTION
**Pull request by pikurasa**
If there is a mailchimp account, please let me know.

### CODE REVIEW

**Comment by chimosky** [comment]
I don't know of any.

**Comment by pikurasa** [comment]
Then please merge this, so that other people don't have the expectation that one exists.

**Comment by chimosky** [comment]
Could you setup 2FA so I'll grant you administrative access?

**Comment by pikurasa** [comment]
> Could you setup 2FA so I'll grant you administrative access?

I'm set up now

**Comment by chimosky** [comment]
Done.

**Pull request merged**
