### PR TITLE
Shift the content below the navbar. Fixes issue #574

### PR DESCRIPTION
**Pull request by AetherSparks**
# Description
Add a dynamic Padding adjuster in index.html, which shifts the content below the navigation bar so no content is hidden.

This Pull Request addresses Issue #574 raised by sahiladit, where some of the Navbar hides the text behind it. By adjusting the content padding, the added script is able to dynamically shift the content of the page below the navigation bar so that none of the content is hidden, even when the screen dimensions are changed.

# Changes Made

See [Files changed](https://github.com/sugarlabs/www/pull/578/files).

# Screenshots

https://github.com/user-attachments/assets/d0eeb8af-03c2-41ba-98d1-337b9b974929

Fixes issue #574

### CODE REVIEW

**Comment by quozl** [comment]
* [ ] your check items in the opening comment of the pull request were without asterisk prefix, edited,
* [ ] your opening comment included a screenshot of changes; use the Files changed link instead, edited,
* [ ] your commit message does not follow our guidelines, and is wrong because the problem is not text not visible in navbar, but navbar is covering content.

**Comment by quozl** [comment]
You have changed the pull request title.  To change the commit message, use `git commit --amend` then `git push --force`.

**Comment by AetherSparks** [comment]
> You have changed the pull request title. To change the commit message, use `git commit --amend` then `git push --force`.

Okay, Thankyou

**Comment by quozl** [comment]
Reviewed 9191ec7.

* [ ] start with a one line summary of the change;
* [ ] leave a blank line after the summary;
* [ ] explain the problem that is solved, unless the summary makes it obvious;
* [ ] when the problem was introduced by a previous commit, mention the hash; (this problem was introduced in the past week),
* [X] when the problem is in an issue or ticket, add "Fixes #1234";
  * [ ] at the end of the message, that is,
* [ ] use imperative mood, like "fix" rather than "fixed",

From [making commits](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits)

The purpose of this guideline is to increase the quality of the history of the repository, so that we can use `git blame` and `git cherry-pick` with ease.

**Comment by pikurasa** [comment]
@AetherSparks We appreciate this. Do you plan on trying once more, following James's guidance?

**Comment by quozl** [comment]
Thanks.  Good progress.  Which items in my comment are you having problems with?

**Comment by pikurasa** [comment]
@AetherSparks I think that you can make the commit message something like: `Shift the content below the navbar. Fixes issue #574`

**Comment by AetherSparks** [comment]
> @AetherSparks I think that you can make the commit message something like: `Shift the content below the navbar. Fixes issue #574`

Noted, I will Implement this right away.

**Comment by quozl** [comment]
Thanks.  Good progress on my comment.  I've updated [the checklist](https://github.com/sugarlabs/www/pull/578#issuecomment-2525289842).  You are welcome to make any further changes to do the unchecked items.

**Comment by pikurasa** [comment]
@AetherSparks This patch does not seem to be an improvement upon the current master branch.

Screenshot from 2024-12-16 12-56-06

**Comment by pikurasa** [comment]
> @pikurasa I'm surprised it is not an improvement.

The results I get are what you can see in the image embedded in my previous comment. The window on the left is this PR branch. The window on the right is the live master branch. On master, the text is well below the navbar. On this branch, there very little space underneath the navbar.

**Comment by AetherSparks** [comment]
> @AetherSparks This patch does not seem to be an improvement upon the current master branch.
> 
> (Left image is this PR branch; right is the live master branch.)
> 
> Screenshot from 2024-12-16 12-56-06

@pikurasa I have opened the official sugarlabs website like the right side of your screenshot, and this is what Im getting.


https://github.com/user-attachments/assets/675e1375-e5f2-428e-9886-59dcfa088f3e

Changing the Dimensions seems to hide the text just like the original issue.

**Comment by AetherSparks** [comment]
> Reviewed [9191ec7](https://github.com/sugarlabs/www/commit/9191ec7cab7afcc2bc82cf00e571daeed9b98409).
> 
> * [x]  start with a one line summary of the change;
> * [x]  leave a blank line after the summary;
> * [x]  explain the problem that is solved, unless the summary makes it obvious;
> * [ ]  when the problem was introduced by a previous commit, mention the hash; (this problem was introduced in the past week),
> * [x]  when the problem is in an issue or ticket, add "Fixes #1234";
>   
>   * [x]  at the end of the message, that is,
> * [x]  use imperative mood, like "fix" rather than "fixed",
> 
> Above adapted from [making commits](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits).
> 
> The purpose of this guideline is to increase the quality of the history of the repository, so that we can use `git blame` and `git cherry-pick` with ease.

@quozl I am relatively new to Sugarlabs, and I do not know in which commit this problem was introduced. Can you provide guidance for this?

**Comment by pikurasa** [comment]
I've tested it some more, and I think what's happening is: For window sizes of width approx. ~800-1000, it is improved. For 1000+, it is unchanged, and for under ~800, it's not an improvement as it looks like my screenshot above.

**Comment by AetherSparks** [comment]
> I've tested it some more, and I think what's happening is: For window sizes of width approx. ~800-1000, it is improved. For 1000+, it is unchanged, and for under ~800, it's not an improvement as it looks like my screenshot above.

I see, After testing it seems that as soon as the Paypal/Visa/MasterCard Image is removed from the navbar the Index is bumped up.
I will work to update this issue.

**Comment by AetherSparks** [comment]
> I've tested it some more, and I think what's happening is: For window sizes of width approx. ~800-1000, it is improved. For 1000+, it is unchanged, and for under ~800, it's not an improvement as it looks like my screenshot above.


I Believe I have fixed the navbar spacing issue for all possible window sizes. Kindly check it out.

https://github.com/user-attachments/assets/ec9d8cfc-9539-4028-827a-8e9dd2c2e625

**Comment by AetherSparks** [comment]
@pikurusa @quozl kindly give your thoughts on this.

**Comment by quozl** [comment]
Thanks for the commit message fix.

**Comment by AetherSparks** [comment]
Will this be merged into master? Or are there any necessary steps I need to go through to progress? Kindly Advice.

**Comment by quozl** [comment]
The problem https://github.com/sugarlabs/www/issues/574 is fixed now, so I'll close this.  Thanks for the effort!  If you have changes to make that are unrelated to the problem, please resubmit them.

**Pull request closed without merging**
