### PR TITLE
Refactor Activity Section Layout and update CSS

### PR DESCRIPTION
**Pull request by soumyaranjan-panda**
Updated the activity section and added styling making it more interactive for teachers, students, and kids.

- Added hover animation for interactive elements.
- Tested responsiveness across different screen sizes.
- Updated [assets/activity-numbers.svg](https://github.com/sugarlabs/www/compare/master...soumyaranjan-panda:www:update-activity-section?expand=1#diff-acf56af56484277a795b96eea6bd830c88f3e1bd093e2924f9d3a7523b79c81f) by removing unnecessary padding on the right and bottom sides.
- Fixed background color inconsistency and merged activity website redirection section with main activity section making it feel cohesive.

### CODE REVIEW

**Comment by quozl** [comment]
Please update the icon in the Numbers activity, thanks.

**Comment by soumyaranjan-panda** [comment]
> Please update the icon in the Numbers activity, thanks.

Sorry, I didn’t quite understand your request. I have updated the number icon with the new one. Would you like me to revert it back, or is there another place where the icon needs to be updated?

**Comment by quozl** [comment]
Oh, you are so missing out.  :grin:

You will remember that your commit [removed the HTML comment markers](https://github.com/sugarlabs/www/pull/594/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L445) from the Numbers Activity elements.  The button you have enabled links to [4336](https://activities.sugarlabs.org/en-US/sugar/addon/4336) in our Python 2 activity library.  The entry in the library points to the GitHub repository for the activity, [here](https://github.com/walterbender/numbers).  That repository has the icon in the activity directory.

So if you're proposing to change that icon, we'd expect you to change it in the activity as well as the web site.  We chose not to automate the fetch or use git submodules.

See also https://github.com/sugarlabs/www/issues/591 for problems with the section you are proposing to change.

**Comment by quozl** [comment]
https://v4.activities.sugarlabs.org/?q=numbers ... is another site where the icon is rendered, you can see the impact on the layout, but this will be fixed once the next release of the Numbers Activity is made after your change there.

**Comment by soumyaranjan-panda** [comment]
> Oh, you are so missing out. 😁

I thought I might need to change the icon in the number activity, but I just wanted to confirm if that’s what you had in mind. Thank you so much for your guidance!

**Comment by quozl** [comment]
Thanks.

* [ ] please remove the merge commit,
* [ ] please rebase on the master branch, as it has since shifted.

**Comment by soumyaranjan-panda** [comment]
I will create a new pull request to address all the issues.

**Comment by quozl** [comment]
Why?  Please learn how to resolve these issues without creating a new pull request.  It is straightforward.  It is difficult to track review comments across multiple pull requests.

**Comment by soumyaranjan-panda** [comment]
> Why? Please learn how to resolve these issues without creating a new pull request. It is straightforward. It is difficult to track review comments across multiple pull requests.

Yes, sir. This will be the last time I create a new pull request. Moving forward, I will ensure all issues are resolved within the same pull request. However, since I have already deleted the branch, it would be difficult to recover it. May I create another pull request to address this?

**Pull request closed without merging**
