### PR TITLE
add community and event pages to website

### PR DESCRIPTION
**Pull request by haroon10725**
@pikurasa Can you please review it.

### CODE REVIEW

**Comment by pikurasa** [comment]
For the navbar, please put a dropdown of "news" that was "community news", "events", and "press releases" (in that order).

**Comment by haroon10725** [comment]
@pikurasa Will do it.

**Comment by pikurasa** [comment]
@haroon10725 I created https://github.com/haroon10725/www/pull/1 to be merged with this branch. Then we can make any final changes and then merge. WDYT?

**Comment by haroon10725** [comment]
Sure @pikurasa

**Pull request merged**
