### PR TITLE
Fix the navbar padding

### PR DESCRIPTION
**Pull request by SrijanVerma04**
Fixes the content in the navbar with equal padding

### CODE REVIEW

**Comment by quozl** [comment]
Thanks, a nice simple change.  Though I don't know why it works.

What do you think of https://github.com/sugarlabs/www/issues/305?  First commit in this repository was a 2017 Google Summer of Code project, which took airspace.css from what is now https://github.com/ndrewtl/airspace-jekyll and made some small changes.  A diff between airspace-jekyll and that original airspace.css from 725368d3bc881bf70b9bf84cf4d5a878426f1035 shows a small degree of change.  Since then we have tended to solve layout and formatting problems by tweaking this further.  Your work on this pull request is another in that long sequence.  Can you think of a way to bring our site back into a situation where we don't have to keep changing the upstream source code in airspace.css?  Does it actually look okay with unmodified airspace.css and the other files?  Should we be using a completely different Jekyll theme now?

**Comment by SrijanVerma04** [comment]
Since I am very new to open source and contributing to the project and just fix the first issue which i think by changing some of the padding can solve the problem. Since appearance is also plays the big role for the website. And for using a different jekyll theme , i think i need to spend some more time before giving any of my opinion.
So with the guidance it will be helpful what to be done for the betterment of this project!!

**Comment by quozl** [comment]
Thanks.  I don't mean a different theme, but the same one ... just without our customisation or derivation.

**Comment by SrijanVerma04** [comment]
okay but for now i don't have any idea How this can be done but i will look into this.

**Comment by PasunuriSrinidhi** [comment]
> Since I am very new to open source and contributing to the project and just fix the first issue which i think by changing some of the padding can solve the problem. Since appearance is also plays the big role for the website. And for using a different jekyll theme , i think i need to spend some more time before giving any of my opinion. So with the guidance it will be helpful what to be done for the betterment of this project!!

Using different Jekyll themes can provide many advantages, including easy customization, pre-built layouts, responsive design, SEO optimization, integration with Jekyll plugins, and community support.

**Pull request closed without merging**
