### PR TITLE
Added "About Sugar Labs" boilerplate to _includes

### LINKED ISSUE #534: Put boiler plate "about Sugar Labs" text into a _includes html
We're going to want to stamp a boiler plate "about Sugar Labs" text on many pages, such as our press releases.

We can copy and paste manually, or we can put the text into _includes as html that we can use again and again. The benefit of doing the latter is that it will be easy to update if we ever decide to make some changes.

Our current text is as follows:
```
## About Sugar Labs

Sugar Labs® is a US-based 501(c)(3) nonprofit organization with a
global mission to create educational opportunities in technology to
youth around the world. Volunteer mentors and contributors work
together to develop activity-focused software for children. All
software is developed with learning as the primary goal, necessitating
the need for source code to be published publicly for study, licensed
under a free/libre license for explicit permission to share and remix,
and openly worked upon within a community where students are invited
to make contributions, under guidance of experienced mentors.
Donations to support the work of Sugar Labs can be made at
<https://www.sugarlabs.org/donate/>.
```

### PR DESCRIPTION
**Pull request by nischal-shetty2**
Fixes #534
by adding a reusable component to the _includes folder for easier updates in one place.

Screenshot 2024-11-07 at 12 29 29 AM

### CODE REVIEW

**Comment by nischal-shetty2** [comment]
hey @pikurasa could you take a look!

**Comment by pikurasa** [comment]
You should also test it by replacing the about text on _posts/2024/05/08/Sugar-Labs-announces-nonprofit-status-new-executive-director/ with your new text.

I also recommend making the link as `{{ site.baseurl }}/donate.html`

**Comment by nischal-shetty2** [comment]
> You should also test it by replacing the about text on _posts/2024/05/08/Sugar-Labs-announces-nonprofit-status-new-executive-director/ with your new text.
> 
> I also recommend making the link as `{{ site.baseurl }}/donate.html`

on it!

**Comment by nischal-shetty2** [comment]
Tested it by adding it on `_posts` here is how it looks @pikurasa 

Screenshot 2024-11-07 at 12 44 38 AM

**Comment by pikurasa** [comment]
Tested. It works. Thanks!

**Comment by nischal-shetty2** [comment]
> Tested. It works. Thanks!

this was my first pr on this repo thank you for being helpful throughout @pikurasa ! happy to contribute!

**Pull request merged**
