### PR TITLE
Fix 545: text color of 'about us' option and 'news' option

### PR DESCRIPTION
**Pull request by Lakshya0257**
Fixed the issue raised in #545 

## Issue
Navbar tabs were showing two different colors in two different window sizes.

## Fix

- Fixed by modifying the nav.html without affecting any other behaviour.

## Output
image
image

### CODE REVIEW

**Comment by therealharshit** [comment]
@Lakshya0257 I think it would be much better if it looks like 

On both the screen size.

**Comment by Lakshya0257** [comment]
@therealharshit I have modified according to your requirements, kindly review it now.

image

**Comment by therealharshit** [comment]
@Lakshya0257 the changes you made didn't fix this issue, it has also also affected the previous behavior of navbar.
Vedio:

https://github.com/user-attachments/assets/78fd092d-b59d-4f3a-afd0-4db242005585

**Comment by Sushant0124** [comment]
@therealharshit  Is the issue is still there??

**Comment by pikurasa** [comment]
@Sushant0124 once you get this "camera ready", please put it on a new branch and open up a new PR. It's a very important habit to get into.

Please refer to https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits for best practices.

**Comment by quozl** [comment]
@Lakshya0257 please review https://github.com/sugarlabs/www/pull/565 and decide if you want https://github.com/sugarlabs/www/pull/550 to continue.

**Comment by quozl** [comment]
You did not respond, so I decided https://github.com/sugarlabs/www/pull/565 was the better solution and merged it.  Closing this pull request.

**Pull request closed without merging**
