### PR TITLE
Dynamic year in copyright section added 

### PR DESCRIPTION
**Pull request by AdityyaX**
This pull request eliminates the manual effort required to update the copyright year in the footer of our website annually.

### CODE REVIEW

**Comment by quozl** [comment]
Copyright law in many jurisdictions would frown upon an automated change that makes a legal claim to have changed content yet without any verification that content has actually changed.  To do this correctly, your code will have to determine _if_ the content has been changed before changing the year.

On the other hand, if our purpose was to make a web site that showed you the current year, what you suggest would be fine.  :grin:

**Comment by quozl** [comment]
Oh, and the way you have written it depends on the year being set correctly on the computer running the web browser, rather than on our server.

**Comment by AdityyaX** [comment]
Is there any proposed changes, or i shall leave this pull request as it is right now?

**Comment by quozl** [comment]
Thanks.  I've given my views.  I'd like to hear from other members of Sugar Labs.

**Comment by chimosky** [comment]
> Copyright law in many jurisdictions would frown upon an automated change that makes a legal claim to have changed content yet without any verification that content has actually changed. To do this correctly, your code will have to determine if the content has been changed before changing the year.

I agree with Quozl on this, the website doesn't change so much and regularly so I'm a bit skeptical about this.

**Comment by pikurasa** [comment]
We appreciate this, but we will not be doing dynamic copyright years.

**Pull request closed without merging**
