### PR TITLE
update: ion icons

### PR DESCRIPTION
**Pull request by haroon10725**
Fixes: #455

### CODE REVIEW

**Comment by haroon10725** [comment]
@pikurasa Can you please review it.

**Comment by pikurasa** [comment]
It seems to work for me.

Please explain here how you made the update. I think we should also add a note about how to do this in the documentation.

**Comment by haroon10725** [comment]
@pikurasa I did "npm i ionicons@7" . This command updated the whole library.

**Comment by haroon10725** [comment]
> > @pikurasa I did "npm i ionicons@7" . This command updated the whole library.
> 
> Please create a new PR with a note of this to our REAMDE.md, under https://github.com/sugarlabs/www?tab=readme-ov-file#how-to-add-new-icons

@pikurasa Will do it.

**Pull request merged**
