### PR TITLE
Fixes #545 text color of "about us" option and "news" option

### LINKED ISSUE #545: text color of "about us" option  and  "news" option
when i adjust width of website to smaller then 1215px , options text color is grey 
i also attach screenshot
Screenshot 2024-11-10 182313
but website width is greater than 1215px , options text color is blue
see below screenshot
Screenshot 2024-11-10 182007
this is responsive error must be resolve that
thank you.

### PR DESCRIPTION
**Pull request by therealharshit**
Fixes #545 
This is how it look like 
dropdown
dropdown 2

@quozl @pikurasa please review.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.

* [ ] does not match the Bootstrap example for the version in use, in that the immediately surrounding element is a ul with class dropdown-menu, instead of a div with class dropdown-menu.

Can you explain why you have chosen ul?

Reference: https://getbootstrap.com/docs/4.0/components/navbar/

**Comment by quozl** [comment]
Thanks.  Reviewed.  Looked at history; was this problem introduced by 7088c6ddb1b9159eaebd8c8b4138dd83962e55f0?  Updated issue.

**Comment by therealharshit** [comment]
> Thanks. Reviewed. Looked at history; was this problem introduced by [7088c6d](https://github.com/sugarlabs/www/commit/7088c6ddb1b9159eaebd8c8b4138dd83962e55f0)? Updated issue.

@quozl No it wasn't that commit aims to resolve the responsiveness of the navbar.
You can see in that commit the dropdown-menu tags are already `<li>` and `<ul>`,
And the code which I added for navbar of mobile devices is perfect.

**Comment by quozl** [comment]
Thanks.  I've dug deeper, the practice was in the original GSoC 2017 commit 725368d, with Bootstrap 3.3.7, for which the documentation is not easily available, but in [tag v3.3.7 file docs/examples/navbar/index.html the practice is clearly present](https://github.com/twbs/bootstrap/blob/v3.3.7/docs/examples/navbar/index.html#L57).

Therefore our upgrade to Bootstrap 4.0.0 in 99eabc0d4eb1dcb53827d42b2f1d257a0b78a73a may have been incomplete.

**Comment by Ajaykumar724** [comment]
> Fixes #545 
> This is how it look like 
> dropdown
> dropdown 2
> 
> @quozl @pikurasa please review.


This is OK 
But navbar text color blue will very expressive

**Comment by quozl** [comment]
Thanks for your patience.  Delay was due to contributions to the issue by others who wanted to fix the problem, but in the end didn't want the problem fixed enough to help us fix it.

**Pull request merged**
