### PR TITLE
feat: add Sugar-Stories page

### PR DESCRIPTION
**Pull request by saumyashahi**
## Summary

Add a new "Sugar Stories" page to showcase community stories. This replaces the old static Sugar Stories page with content from markdown files in the "stories" category.

## Key Changes

- Create `sugar-stories.html` for the new page.
- Implement markdown syntax posts into the "stories" category.
- Automate story uploads by adding markdown files.

## Testing

- Verify responsiveness and styling on different devices.
- Check for acknowledgements for particular stories.

### CODE REVIEW

**Comment by saumyashahi** [comment]
@pikurasa 
I have implemented the sugar-stories page on the story that was already available on the sugarlabs.org page, if this is approved then we can add stories from medium and other platforms. The only work left will be to convert them to markdown files.

**Comment by MostlyKIGuess** [comment]
I will also be adding something here and finish #571.

**Comment by MostlyKIGuess** [comment]
Worked and added #618 . Grateful for the initial input.

**Comment by MostlyKIGuess** [comment]
@saumyashahi we can close this ig

**Comment by saumyashahi** [comment]
yes sure!

**Pull request closed without merging**
