### PR TITLE
Create Privacy-policy.html

### PR DESCRIPTION
**Pull request by nathan-jacob**

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Fixes https://github.com/sugarlabs/www-sugarlabs/issues/237

* where did this text come from?
* what is the copyright?
* are you a member of Sugar Labs?
* has this policy been approved by the Sugar Labs Oversight Board?

@walterbender, has the board considered this policy?  It makes several promises that seem unlikely to be resourced.

**Comment by nathan-jacob** [comment]
The text comes from another openly sourced organization that makes basic privacy policies for smaller companies. The copyright is 100% ours. I am not currently a member of sugar labs although I have contributed a lot before. I have not gotten it approved by the oversight board, although I did run it by Samson Goddy.

**Comment by quozl** [comment]
Thanks.  What is the other organisation?

**Comment by nathan-jacob** [comment]
FreePrivacyPolicy.com

**Comment by quozl** [comment]
Thanks.  The [terms of use](https://www.freeprivacypolicy.com/terms-of-use.html) have a section on copyright that looks worrying.  @walterbender, what do you think?

**Comment by quozl** [comment]
See our Wiki [privacy policy](https://wiki.sugarlabs.org/go/Sugar_Labs:Privacy_policy) which also contains a link to our parent organisation's privacy policy.

**Comment by walterbender** [comment]
First, thanks for pushing this along. It is important that we make this clear to our users. That said, I think we need to do things a bit differently.
(1) As Quozl points out, we are bound by the policies of the SFC, so we should point that out up front.
(2) Some of the tools we use as a community, e.g., git, github, mediawiki, do collect some information about our developers and contributors.
(3) It is the Sugar Labs policy to never use any personal information about our users.

I am not sure how we codify all of the above.

**Comment by nathan-jacob** [comment]
Here I fixed the changes you mentioned

**Pull request closed without merging**
